# Generated by Django 5.2.16 on 2026-07-24 04:51

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0002_seed_master_data'),
        ('students', '0008_auto_20260716_1052'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('report_month', models.PositiveSmallIntegerField(db_index=True)),
                ('report_year', models.PositiveSmallIntegerField(db_index=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('mobile_recovery_count', models.PositiveIntegerField(default=0)),
                ('financial_recovery_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft', max_length=20)),
                ('admin_remarks', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='investigator/recovery_reports/')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fraud_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_reports', to='investigator.fraudtype')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_reports', to='investigator.policestation')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigator_recovery_reports', to='students.studentadmission')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_recovery_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approval_status', '-created_at'], name='investigato_approva_a257a5_idx'), models.Index(fields=['report_year', 'report_month'], name='investigato_report__43cc8f_idx')],
            },
        ),
    ]
