# Generated by Django 5.2.16 on 2026-07-24 06:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0003_recoveryreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('case_no', models.CharField(max_length=120)),
                ('investigating_officer', models.CharField(max_length=180)),
                ('case_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], db_index=True, default='Pending', max_length=20)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft', max_length=20)),
                ('admin_remarks', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='investigator/case_work_reports/')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_work_reports', to='investigator.policestation')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_case_work_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=180)),
                ('work_description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='investigator.caseworkreport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='caseworkreport',
            index=models.Index(fields=['approval_status', '-created_at'], name='investigato_approva_52d1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='caseworkreport',
            index=models.Index(fields=['case_status', '-created_at'], name='investigato_case_st_41aba4_idx'),
        ),
    ]
