# Generated by Django 5.2.16 on 2026-07-24 06:31

from django.db import migrations, models


def copy_student_name_to_name(apps, schema_editor):
    RecoveryReport = apps.get_model('investigator', 'RecoveryReport')
    for report in RecoveryReport.objects.select_related('student').filter(name=''):
        if report.student_id:
            report.name = report.student.student_name
            report.save(update_fields=['name'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0004_caseworkreport_caseworkitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryreport',
            name='name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.RunPython(copy_student_name_to_name, noop_reverse),
    ]
