# Generated by Django 5.2.16 on 2026-07-24 06:46

from django.db import migrations


def user_display_name(user):
    first_name = (getattr(user, 'first_name', '') or '').strip()
    last_name = (getattr(user, 'last_name', '') or '').strip()
    full_name = f'{first_name} {last_name}'.strip()
    return full_name or user.username


def set_report_names_from_investigator(apps, schema_editor):
    RecoveryReport = apps.get_model('investigator', 'RecoveryReport')
    CaseWorkReport = apps.get_model('investigator', 'CaseWorkReport')

    for report in RecoveryReport.objects.select_related('submitted_by').filter(submitted_by__isnull=False):
        report.name = user_display_name(report.submitted_by)
        report.save(update_fields=['name'])

    for report in CaseWorkReport.objects.select_related('submitted_by').filter(submitted_by__isnull=False):
        report.name = user_display_name(report.submitted_by)
        report.save(update_fields=['name'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0005_recoveryreport_name'),
    ]

    operations = [
        migrations.RunPython(set_report_names_from_investigator, noop_reverse),
    ]
