# Generated by Django 5.1.4 on 2026-06-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feedback_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('center', 'Center'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=10),
        ),
    ]
