# Generated by Django 5.1.4 on 2026-06-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('center', 'Center'), ('teacher', 'Teacher'), ('student', 'Student'), ('telecaller', 'Telecaller')], max_length=15),
        ),
    ]
