# Generated by Django 5.1.4 on 2026-06-23 04:41

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.ActiveUserManager()),
                ('all_objects', apps.accounts.models.AllUserManager()),
            ],
        ),
    ]
