# Generated by Django 5.1.4 on 2026-06-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin'), ('center', 'Center'), ('teacher', 'Teacher'), ('student', 'Student'), ('hr', 'HR'), ('telecaller', 'Telecaller'), ('counselor', 'Counselor')], max_length=15),
        ),
    ]
