# Generated by Django 5.1.4 on 2026-06-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
        ('accounts', '0013_rename_authactivitylog_indexes'),
    ]

    operations = [
    ]
