# Generated by Django 4.2.23 on 2026-06-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20260627_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('admin', 'Admin'), ('superadmin', 'Super Admin'), ('center', 'Center'), ('teacher', 'Teacher'), ('student', 'Student'), ('hr', 'HR'), ('telecaller', 'Telecaller'), ('counselor', 'Counselor')], max_length=20),
        ),
    ]
