from django.urls import path

from . import views


urlpatterns = [
    path('', views.investigator_dashboard, name='investigator_dashboard'),
    path('recovery-reports/', views.recovery_reports, name='investigator_recovery_reports'),
    path('recovery-reports/export/', views.recovery_report_export, name='investigator_recovery_export'),
    path('recovery-reports/pdf/', views.recovery_report_pdf, name='investigator_recovery_pdf'),
    path('recovery-reports/print/', views.recovery_report_print, name='investigator_recovery_print'),
    path('recovery-reports/add/', views.recovery_report_add, name='investigator_recovery_add'),
    path('recovery-reports/<int:pk>/', views.recovery_report_detail, name='investigator_recovery_detail'),
    path('recovery-reports/<int:pk>/edit/', views.recovery_report_edit, name='investigator_recovery_edit'),
    path('recovery-reports/<int:pk>/delete/', views.recovery_report_delete, name='investigator_recovery_delete'),
    path('recovery-reports/<int:pk>/submit/', views.recovery_report_submit, name='investigator_recovery_submit'),
    path('recovery-reports/<int:pk>/<str:action>/', views.recovery_report_review, name='investigator_recovery_review'),
    path('case-work-reports/', views.case_work_reports, name='investigator_case_work_reports'),
    path('case-work-reports/export/', views.case_work_report_export, name='investigator_case_work_export'),
    path('case-work-reports/pdf/', views.case_work_report_pdf, name='investigator_case_work_pdf'),
    path('case-work-reports/print/', views.case_work_report_print, name='investigator_case_work_print'),
    path('case-work-reports/add/', views.case_work_report_add, name='investigator_case_work_add'),
    path('case-work-reports/<int:pk>/', views.case_work_report_detail, name='investigator_case_work_detail'),
    path('case-work-reports/<int:pk>/edit/', views.case_work_report_edit, name='investigator_case_work_edit'),
    path('case-work-reports/<int:pk>/delete/', views.case_work_report_delete, name='investigator_case_work_delete'),
    path('case-work-reports/<int:pk>/submit/', views.case_work_report_submit, name='investigator_case_work_submit'),
    path('case-work-reports/<int:pk>/<str:action>/', views.case_work_report_review, name='investigator_case_work_review'),
    path('investigator-wise-report/', views.investigator_wise_report, name='investigator_wise_report'),
    path('investigator-wise-report/export/', views.investigator_wise_report_export, name='investigator_wise_report_export'),
    path('investigator-wise-report/pdf/', views.investigator_wise_report_pdf, name='investigator_wise_report_pdf'),
    path('investigator-wise-report/print/', views.investigator_wise_report_print, name='investigator_wise_report_print'),
    path('universal-report/', views.universal_report, name='investigator_universal_report'),
    path('universal-report/export/', views.universal_report_export, name='investigator_universal_report_export'),
    path('universal-report/pdf/', views.universal_report_pdf, name='investigator_universal_report_pdf'),
    path('universal-report/print/', views.universal_report_print, name='investigator_universal_report_print'),
    path('approval-review/', views.approval_review, name='investigator_approval_review'),
    path('master-settings/', views.master_settings, name='investigator_master_settings'),
    path('user-management/', views.investigator_user_management, name='investigator_user_management'),
    path('user-management/<int:pk>/edit/', views.investigator_user_edit, name='investigator_user_edit'),
    path('user-management/<int:pk>/toggle/', views.investigator_user_toggle, name='investigator_user_toggle'),
    path('master-settings/fraud-types/', views.fraud_type_list, name='investigator_fraud_type_list'),
    path('master-settings/fraud-types/<int:pk>/edit/', views.fraud_type_edit, name='investigator_fraud_type_edit'),
    path('master-settings/fraud-types/<int:pk>/toggle/', views.fraud_type_toggle, name='investigator_fraud_type_toggle'),
    path('master-settings/police-stations/', views.police_station_list, name='investigator_police_station_list'),
    path('master-settings/police-stations/<int:pk>/edit/', views.police_station_edit, name='investigator_police_station_edit'),
    path('master-settings/police-stations/<int:pk>/toggle/', views.police_station_toggle, name='investigator_police_station_toggle'),
    path('export-print/', views.export_print, name='investigator_export_print'),
]
