# Generated by Django 4.2.23 on 2026-07-06 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_soft_delete_fields'),
        ('students', '0005_studentadmission_approved_at_and_more'),
        ('academics', '0002_academicsession_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0002_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='centers.center'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='examination_conducted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.studentadmission'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'session', 'course_duration')},
        ),
        migrations.AlterModelTable(
            name='certificate',
            table='certificates_certificate',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='status',
        ),
    ]
