# Generated by Django 5.2.15 on 2026-07-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
