# Generated by Django 5.1.4 on 2026-07-03 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_soft_delete_fields'),
        ('courses', '0004_alter_course_center'),
        ('students', '0003_soft_delete_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('enrollment_no', models.CharField(max_length=100, unique=True)),
                ('timetable_course', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_no', models.CharField(max_length=20)),
                ('alt_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('family_id', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('medium', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admission_photos/')),
                ('pincode', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('passed_exam', models.CharField(blank=True, max_length=255, null=True)),
                ('marks_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('board', models.CharField(blank=True, max_length=255, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='admission_docs/')),
                ('aadhar_no', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_form_doc', models.FileField(blank=True, null=True, upload_to='admission_docs/')),
                ('family_id_doc', models.FileField(blank=True, null=True, upload_to='admission_docs/')),
                ('marksheet_10th', models.FileField(blank=True, null=True, upload_to='admission_docs/')),
                ('marksheet_10th_plus', models.FileField(blank=True, null=True, upload_to='admission_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='centers.center')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='courses.course')),
            ],
            options={
                'db_table': 'exam_studentadmission',
            },
        ),
    ]
