# Generated by Django 5.2.15 on 2026-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentadmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course_fee_at_admission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The locked course fee at the time of admission approval.', max_digits=10, null=True),
        ),
    ]
