# Generated by Django 5.2.15 on 2026-07-16 05:22

from django.db import migrations


def backfill_course_fees(apps, schema_editor):
    StudentProfile = apps.get_model('students', 'StudentProfile')
    profiles = StudentProfile.objects.select_related('batch__course').all()
    for profile in profiles:
        if profile.course_fee_at_admission is None:
            if profile.batch and profile.batch.course:
                profile.course_fee_at_admission = profile.batch.course.fees
                profile.save(update_fields=['course_fee_at_admission'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentprofile_course_fee_at_admission'),
    ]

    operations = [
        migrations.RunPython(backfill_course_fees, reverse_code=migrations.RunPython.noop),
    ]
