# Generated by Django 4.2.23 on 2026-07-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='aadhar_doc',
            field=models.FileField(blank=True, null=True, upload_to='centers/docs/'),
        ),
        migrations.AddField(
            model_name='center',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='centers/docs/'),
        ),
        migrations.AddField(
            model_name='center',
            name='agreement_doc',
            field=models.FileField(blank=True, null=True, upload_to='centers/docs/'),
        ),
        migrations.AddField(
            model_name='center',
            name='classrooms_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='center',
            name='computers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='center',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='center',
            name='has_reception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='center',
            name='has_staff_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='center',
            name='has_toilet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='center',
            name='has_water_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='center',
            name='head_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='logo_doc',
            field=models.ImageField(blank=True, null=True, upload_to='centers/logos/'),
        ),
        migrations.AddField(
            model_name='center',
            name='owner_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='owner_image',
            field=models.ImageField(blank=True, null=True, upload_to='centers/owners/'),
        ),
        migrations.AddField(
            model_name='center',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='signature_doc',
            field=models.ImageField(blank=True, null=True, upload_to='centers/docs/'),
        ),
        migrations.AddField(
            model_name='center',
            name='space_sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='center',
            name='staff_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='center',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
