# Generated by Django 4.2.23 on 2026-07-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_center_aadhar_doc_center_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='prefix_roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
