# Generated by Django 4.2.23 on 2026-07-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_center'),
        ('centers', '0004_center_prefix_roll_no_center_valid_upto'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, related_name='assigned_centers', to='courses.course'),
        ),
    ]
