# Generated by Django 5.1.4 on 2026-07-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_centercourseassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centercourseassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
