# Generated by Django 5.2.15 on 2026-07-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_alter_centercourseassignment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='assigned_courses',
        ),
    ]
