# Generated by Django 5.2.15 on 2026-07-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_remove_center_assigned_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
