# Generated by Django 5.2.15 on 2026-07-01 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_soft_delete_fields'),
        ('courses', '0003_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.center'),
        ),
    ]
