# Generated by Django 5.2.15 on 2026-07-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='center',
        ),
    ]
