# Generated by Django 5.2.15 on 2026-06-21 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('qualification', models.CharField(blank=True, max_length=180)),
                ('experience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_company', models.CharField(blank=True, max_length=180)),
                ('skills', models.TextField(blank=True)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applying_position', models.CharField(max_length=160)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, choices=[('naukri', 'Naukri.com'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('website', 'Website'), ('campus', 'Campus'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('new', 'New Candidate'), ('called', 'Called'), ('no_response', 'No Response'), ('follow_up_pending', 'Follow-up Pending'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('joined', 'Joined'), ('on_hold', 'On Hold')], default='new', max_length=30)),
                ('resume', models.FileField(blank=True, upload_to='hr/resumes/')),
                ('photo', models.ImageField(blank=True, upload_to='hr/candidates/')),
                ('certificates', models.FileField(blank=True, upload_to='hr/certificates/')),
                ('date_added', models.DateField(default=django.utils.timezone.localdate)),
                ('last_call_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_hr', models.ForeignKey(blank=True, limit_choices_to={'role': 'hr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_candidates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_created_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CandidateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Candidate Added'), ('call', 'Call Completed'), ('followup', 'Follow-up Added'), ('interview', 'Interview Scheduled'), ('feedback', 'Interview Conducted'), ('status', 'Status Changed'), ('note', 'Note Added'), ('document', 'Document Updated')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='hr.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='hr.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('follow_up_time', models.TimeField()),
                ('follow_up_type', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('meeting', 'Meeting')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('call_later', 'Call Later'), ('interview_scheduled', 'Interview Scheduled'), ('no_response', 'No Response')], max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='hr.candidate')),
                ('handled_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'hr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['follow_up_date', 'follow_up_time'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('hr', 'HR Round'), ('technical', 'Technical Round'), ('final', 'Final Round')], max_length=20)),
                ('interviewer', models.CharField(max_length=160)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('meeting_link', models.URLField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=220)),
                ('communication', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('technical_skills', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('select', 'Select'), ('reject', 'Reject'), ('hold', 'Hold')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='hr.candidate')),
                ('scheduled_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'hr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
