# Generated by Django 5.2.15 on 2026-06-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_externalemployee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdrive',
            name='package',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
