# Generated by Django 5.2.15 on 2026-06-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_placement_drive_package_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementcompany',
            name='package_offered',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placementoffer',
            name='offered_package',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectallocation',
            name='billing_rate',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectcompany',
            name='project_value',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdrive',
            name='project_value',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
