# Generated by Django 5.2.15 on 2026-06-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_convert_monetary_fields_to_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='externalemployee',
            name='certificates',
        ),
    ]
