# Generated by Django 5.2.15 on 2026-07-16 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_center'),
        ('hr', '0016_candidate_source_free_text'),
        ('students', '0006_studentadmission_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placementcompany',
            name='additional_job_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='placementcompany',
            name='job_role',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='placementcompany',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='placementcompany',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='resume_submission_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementstudentassignment',
            name='interview_attendance',
            field=models.CharField(choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='placementstudentassignment',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementstudentassignment',
            name='offered_ctc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='placementstudentassignment',
            name='offered_role',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='placementstudentassignment',
            name='resume',
            field=models.FileField(blank=True, upload_to='hr/placement/resumes/'),
        ),
        migrations.AddField(
            model_name='placementstudentassignment',
            name='resume_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('submitted', 'Submitted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='placementstudentassignment',
            name='resume_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placementactivity',
            name='activity_type',
            field=models.CharField(choices=[('company', 'Company Added'), ('drive', 'Drive Created'), ('assignment', 'Students Assigned'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Updated'), ('result', 'Result Published'), ('batch', 'Batch Updated'), ('email', 'Email Sent'), ('resume', 'Resume Updated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('scheduled', 'Scheduled'), ('resume_requested', 'Resume Requested'), ('resumes_sent', 'Resumes Sent'), ('interviewing', 'Interviewing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='placementstudentassignment',
            name='final_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('joined', 'Joined')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PlacementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('academic_year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_batches', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='drives', to='hr.placementbatch'),
        ),
        migrations.CreateModel(
            name='PlacementBatchImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('errors', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='hr.placementbatch')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementBatchStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('course_name', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='hr.placementbatch')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_students_imported', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_batch_links', to='students.studentprofile')),
            ],
            options={
                'ordering': ['full_name'],
                'unique_together': {('batch', 'enrollment_no')},
            },
        ),
        migrations.AddField(
            model_name='placementstudentassignment',
            name='batch_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='hr.placementbatchstudent'),
        ),
        migrations.AlterUniqueTogether(
            name='placementstudentassignment',
            unique_together={('drive', 'batch_student')},
        ),
        migrations.CreateModel(
            name='PlacementEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('resume_request', 'Resume Request'), ('company_resumes', 'Resumes To Company'), ('interview', 'Interview Notification'), ('final_result', 'Final Result')], max_length=30)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='skipped', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='hr.placementstudentassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='hr.placementdrive')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
