# Generated by Django 5.2.15 on 2026-07-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_academicsession_occupation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicSession',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
