# Generated by Django 5.2.15 on 2026-07-09 06:31

import django.db.models.deletion
from django.db import migrations, models

import logging

def migrate_batch_centers(apps, schema_editor):
    Batch = apps.get_model("batches", "Batch")
    CenterCourseAssignment = apps.get_model("centers", "CenterCourseAssignment")
    
    for batch in Batch.objects.all():
        if getattr(batch, 'course_id', None):
            assignments = CenterCourseAssignment.objects.filter(course_id=batch.course_id, is_active=True)
            count = assignments.count()
            if count == 1:
                batch.center_id = assignments.first().center_id
                batch.save(update_fields=['center'])
            elif count > 1:
                logger = logging.getLogger(__name__)
                logger.error(f"Batch {batch.id} has multiple active centers for its course. Cannot safely auto-assign center.")

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_delete_academicsession_delete_occupation_and_more'),
        ('centers', '0007_alter_centercourseassignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='centers.center'),
        ),
        migrations.RunPython(
            migrate_batch_centers,
            reverse_code=reverse_migration
        ),
    ]
