# Generated by Django 5.2.15 on 2026-07-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_alter_course_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_offset', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('subject_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Both', 'Both')], default='Theory', max_length=20)),
                ('theory_max_marks', models.IntegerField(blank=True, default=100, null=True)),
                ('theory_min_marks', models.IntegerField(blank=True, null=True)),
                ('practical_max_marks', models.IntegerField(blank=True, default=100, null=True)),
                ('practical_min_marks', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
