# Generated by Django 5.1.4 on 2026-06-19 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_followup_reminder_sent_alter_lead_status_leadimport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImportErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='management.leadimport')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('STATUS_CHANGED', 'Status Changed'), ('CALL_LOG_ADDED', 'Call Log Added'), ('FOLLOWUP_CREATED', 'Follow-Up Created'), ('FOLLOWUP_COMPLETED', 'Follow-Up Completed'), ('NOTE_ADDED', 'Note Added'), ('ASSIGNED', 'Lead Assigned')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='management.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
