# Generated by Django 5.1.4 on 2026-06-19 10:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_lead_assigned_at_lead_assigned_by_importerrorlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='outcome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_counselor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_counselor_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='counselor_status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('COUNSELING_DONE', 'Counseling Done'), ('FOLLOW_UP_REQUIRED', 'Follow Up Required'), ('INTERESTED', 'Interested'), ('CONVERTED', 'Converted'), ('NOT_INTERESTED', 'Not Interested'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=25),
        ),
        migrations.AddField(
            model_name='lead',
            name='counselor_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Missed', 'Missed')], default='Pending', max_length=15),
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('discussion_notes', models.TextField()),
                ('career_guidance_notes', models.TextField(blank=True)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='management.lead')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
    ]
