# Generated by Django 5.1.4 on 2026-06-19 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_followup_outcome_lead_assigned_counselor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interest_level',
            field=models.CharField(choices=[('HIGH_INTEREST', 'High Interest'), ('MEDIUM_INTEREST', 'Medium Interest'), ('LOW_INTEREST', 'Low Interest')], db_index=True, default='MEDIUM_INTEREST', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('TOO_EXPENSIVE', 'Too Expensive'), ('NO_RESPONSE', 'No Response'), ('JOINED_COMPETITOR', 'Joined Competitor'), ('NOT_INTERESTED', 'Not Interested'), ('SERVICE_NOT_MATCHING', 'Service Not Matching'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('STATUS_CHANGED', 'Status Changed'), ('CALL_LOG_ADDED', 'Call Log Added'), ('FOLLOWUP_CREATED', 'Follow-Up Created'), ('FOLLOWUP_COMPLETED', 'Follow-Up Completed'), ('NOTE_ADDED', 'Note Added'), ('ASSIGNED', 'Lead Assigned'), ('INTEREST_LEVEL_CHANGED', 'Interest Level Changed'), ('REASSIGNED', 'Lead Reassigned')], max_length=30),
        ),
        migrations.CreateModel(
            name='LeadReassignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reassigned_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_history', to='management.lead')),
                ('new_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_to_counselors', to=settings.AUTH_USER_MODEL)),
                ('previous_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_from_counselors', to=settings.AUTH_USER_MODEL)),
                ('reassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reassigned_at'],
            },
        ),
    ]
