# Generated by Django 5.1.4 on 2026-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_lead_interest_level_lead_lost_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='interest_level',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lost_reason',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lost_remarks',
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('STATUS_CHANGED', 'Status Changed'), ('CALL_LOG_ADDED', 'Call Log Added'), ('FOLLOWUP_CREATED', 'Follow-Up Created'), ('FOLLOWUP_COMPLETED', 'Follow-Up Completed'), ('NOTE_ADDED', 'Note Added'), ('ASSIGNED', 'Lead Assigned')], max_length=20),
        ),
        migrations.DeleteModel(
            name='LeadReassignmentHistory',
        ),
    ]
