# Generated by Django 5.1.4 on 2026-06-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_visitsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='call_status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('BUSY', 'Busy'), ('NO_ANSWER', 'No Answer'), ('CALL_BACK', 'Call Back'), ('WRONG_NUMBER', 'Wrong Number'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested')], db_index=True, default='NEW', max_length=25),
        ),
    ]
