# Generated by Django 5.1.4 on 2026-06-22 11:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_inquiry_call_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('admission_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('admission_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING_PAYMENT', 'Pending Payment'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=20)),
                ('student_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('parent_mobile', models.CharField(blank=True, max_length=15)),
                ('college_name', models.CharField(blank=True, max_length=300)),
                ('university_name', models.CharField(blank=True, max_length=300)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('admission_source', models.CharField(blank=True, max_length=100)),
                ('course_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('seat_status', models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='BOOKED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_admissions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admissions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sheet', to='management.lead')),
            ],
            options={
                'ordering': ['-admission_date', '-created_at'],
            },
        ),
    ]
