# Generated by Django 5.1.4 on 2026-06-23 05:46

from django.db import migrations

def migrate_pending_payment(apps, schema_editor):
    AdmissionSheet = apps.get_model('management', 'AdmissionSheet')
    AdmissionSheet.objects.filter(admission_status='PENDING_PAYMENT').update(admission_status='PENDING')

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_soft_delete_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_pending_payment, migrations.RunPython.noop)
    ]
