# Generated by Django 5.1.4 on 2026-06-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_migrate_pending_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionsheet',
            name='course_fees',
        ),
        migrations.RemoveField(
            model_name='admissionsheet',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='admissionsheet',
            name='fees_paid',
        ),
        migrations.RemoveField(
            model_name='admissionsheet',
            name='final_fees',
        ),
        migrations.RemoveField(
            model_name='admissionsheet',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='admissionsheet',
            name='remaining_fees',
        ),
        migrations.RemoveField(
            model_name='admissionsheet',
            name='transaction_reference',
        ),
        migrations.AddField(
            model_name='admissionsheet',
            name='batch_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionsheet',
            name='admission_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Follow Up', 'Follow Up'), ('Qualified', 'Qualified'), ('Rejected', 'Rejected'), ('Invalid Number', 'Invalid Number')], db_index=True, default='New', max_length=20),
        ),
    ]
