# Generated by Django 5.1.4 on 2026-06-23 05:53

from django.db import migrations

def migrate_status(apps, schema_editor):
    Lead = apps.get_model('management', 'Lead')
    # Update 'Admission Done' to 'Qualified' for Tele Caller leads
    Lead.objects.filter(status='Admission Done').update(status='Qualified')

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_admissionsheet_course_fees_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_status, reverse_code=migrations.RunPython.noop),
    ]
