# Generated by Django 5.1.4 on 2026-06-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_migrate_telecaller_status_admission_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsheet',
            name='document_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('VERIFIED', 'Verified')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionsheet',
            name='fee_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
