# Generated by Django 5.1.4 on 2026-06-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_admissionsheet_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='counselor_status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('COUNSELING_DONE', 'Counseling Done'), ('FOLLOW_UP_REQUIRED', 'Follow Up Required'), ('INTERESTED', 'Interested'), ('CONVERTED', 'Converted'), ('ADMISSION', 'Admission'), ('NOT_INTERESTED', 'Not Interested'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('Cold', 'Cold'), ('Warm', 'Warm'), ('Hot', 'Hot')], db_index=True, default='Warm', max_length=10),
        ),
    ]
