# Generated by Django 5.2.15 on 2026-06-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_lead_counselor_status_alter_lead_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='call_status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('BUSY', 'Busy'), ('NO_ANSWER', 'Ringing'), ('CALL_BACK', 'Call Back'), ('WRONG_NUMBER', 'Wrong Number'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('PENDING_FOLLOW_UP', 'Pending Follow Up')], db_index=True, default='NEW', max_length=25),
        ),
    ]
