# Generated by Django 5.2.15 on 2026-06-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_inquiry_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='counselor_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='telecaller_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
