# Generated by Django 5.2.15 on 2026-07-01 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_lead_converted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['is_deleted', 'created_at'], name='mg_inquiry_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['is_deleted', 'call_status'], name='mg_inquiry_del_call_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['is_deleted', 'status'], name='mg_inquiry_del_status_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['is_deleted', 'call_date'], name='mg_call_del_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['is_deleted', 'created_by'], name='mg_call_del_user_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['is_deleted', 'status', 'followup_date'], name='mg_follow_del_status_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['is_deleted', 'created_by', 'status', 'followup_date'], name='mg_follow_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted', 'created_at'], name='mg_lead_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted', 'assigned_at'], name='mg_lead_del_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted', 'converted_at'], name='mg_lead_del_converted_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted', 'assigned_counselor', 'converted_at'], name='mg_lead_counsel_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted', 'assigned_telecaller', 'assigned_at'], name='mg_lead_tc_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted', 'first_assigned_user', 'converted_at'], name='mg_lead_owner_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted', 'counselor_status', 'counselor_status_updated_at'], name='mg_lead_cstat_date_idx'),
        ),
    ]
