# Generated by Django 5.2.15 on 2026-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_calllog_mg_call_del_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='call_status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('BUSY', 'Busy'), ('NO_ANSWER', 'Ringing'), ('CALL_BACK', 'Call Back'), ('CALL_DISCONNECTED', 'Call Disconnected'), ('WRONG_NUMBER', 'Wrong Number'), ('INTERESTED', 'Interested'), ('SWITCHED_OFF', 'Switched Off'), ('PENDING_FOLLOW_UP', 'Pending Follow Up'), ('OTHER', 'Other')], db_index=True, default='NEW', max_length=25),
        ),
    ]
