# Generated by Django 5.2.15 on 2026-07-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('batches', '0005_delete_academicsession_delete_occupation_and_more'),
        ('students', '0005_studentadmission_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'batch', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('holiday', 'Holiday'), ('half_day', 'Half Day')], default='present', max_length=10),
        ),
    ]
