# Generated by Django 4.2.23 on 2026-07-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_delete_academicsession_delete_occupation_and_more'),
        ('attendance', '0002_extend_attendance_status_and_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='timetable_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='batches.batch'),
        ),
    ]
