# Generated by Django 4.2.23 on 2026-07-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentadmission_approved_at_and_more'),
        ('attendance', '0003_attendance_timetable_name_alter_attendance_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.studentadmission'),
        ),
    ]
