# Generated by Django 4.2.23 on 2026-07-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentadmission_approved_at_and_more'),
        ('attendance', '0004_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'timetable_name', 'date')},
        ),
    ]
