# Generated by Django 4.2.30 on 2026-06-11 18:29
# Copied from exam/migrations/0002_exam_allow_retake_exam_end_date_exam_negative_marks_and_more.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_retake',
            field=models.BooleanField(default=False, help_text='Allow students to reattempt this exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Last date/time students can attempt this exam (leave blank for no deadline)', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='negative_marks',
            field=models.FloatField(default=0, help_text='Marks deducted for each wrong answer (0 = disabled)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=40, help_text='Minimum % required to pass this exam'),
        ),
    ]
