# Generated by Django 5.1.4 on 2026-06-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('exam', '0003_transfer_profiles_to_dedicated_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='exams', to='batches.batch'),
        ),
    ]
