# Generated by Django 5.2.15 on 2026-07-03 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicsession_status'),
        ('centers', '0002_soft_delete_fields'),
        ('courses', '0004_alter_course_center'),
        ('exam', '0005_soft_delete_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules_center', to='centers.center')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='courses.course')),
                ('exam_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules_exam_center', to='centers.center')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.academicsession')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
