# Generated by Django 5.2.15 on 2026-07-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_examstudentassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('centre_name', models.CharField(max_length=255, verbose_name='Centre Name')),
                ('centre_code', models.CharField(max_length=50, unique=True, verbose_name='Centre Code')),
                ('address', models.TextField(verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Centre',
                'verbose_name_plural': 'Exam Centres',
                'ordering': ['-id'],
            },
        ),
    ]
