# Generated by Django 5.1.4 on 2026-07-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_exam_centre_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='exam_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules_exam_center', to='exam.examcentre'),
        ),
    ]
