# Generated by Django 5.2.15 on 2026-07-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_examschedule_exam_center'),
        ('subjects', '0002_subjectorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_schedules', to='exam.examschedule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedule_rows', to='subjects.subject')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('schedule', 'subject')},
            },
        ),
    ]
