# Generated by Django 5.2.15 on 2026-07-07 06:13

import apps.study_material.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0002_soft_delete_fields'),
        ('courses', '0004_alter_course_center'),
        ('subjects', '0002_subjectorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('course_duration', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('PPT', 'PPT'), ('Excel', 'Excel'), ('ZIP', 'ZIP'), ('Image', 'Image'), ('Video Link', 'Video Link')], max_length=50)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=apps.study_material.models.study_material_upload_path)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='centers.center')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='courses.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='subjects.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_studymaterial',
                'unique_together': {('center', 'course', 'course_duration', 'subject', 'title')},
            },
        ),
    ]
