# Generated by Django 5.2.15 on 2026-07-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_soft_delete_fields'),
        ('courses', '0004_alter_course_center'),
        ('study_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studymaterial',
            unique_together={('center', 'course', 'title')},
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='course_duration',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='subject',
        ),
    ]
