from django.urls import path

from . import views

app_name = 'hr'

urlpatterns = [
    path('signup/', views.signup_hr, name='signup'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('candidates/', views.candidate_list, name='candidate_list'),
    path('candidates/add/', views.candidate_create, name='candidate_create'),
    path('candidates/<int:candidate_id>/', views.candidate_detail, name='candidate_detail'),
    path('candidates/<int:candidate_id>/edit/', views.candidate_edit, name='candidate_edit'),
    path('candidates/<int:candidate_id>/delete/', views.candidate_delete, name='candidate_delete'),
    path('candidates/<int:candidate_id>/call/', views.mark_call, name='mark_call'),
    path('candidates/<int:candidate_id>/status/', views.change_candidate_status, name='change_candidate_status'),
    path('candidates/<int:candidate_id>/notes/add/', views.add_note, name='add_note'),
    path('candidates/<int:candidate_id>/follow-ups/add/', views.followup_create, name='candidate_followup_create'),
    path('candidates/<int:candidate_id>/interviews/schedule/', views.interview_create, name='candidate_interview_create'),
    path('follow-ups/', views.followup_list, name='followup_list'),
    path('follow-ups/add/', views.followup_create, name='followup_create'),
    path('follow-ups/<int:followup_id>/edit/', views.followup_edit, name='followup_edit'),
    path('interviews/', views.interview_list, name='interview_list'),
    path('interviews/schedule/', views.interview_create, name='interview_create'),
    path('interviews/<int:interview_id>/feedback/', views.interview_feedback, name='interview_feedback'),
    path('reports/', views.reports, name='reports'),
    path('performance/', views.performance, name='performance'),
    path('export/candidates/', views.export_candidates, name='export_candidates'),
    path('placement/', views.placement_dashboard, name='placement_dashboard'),
    path('placement/companies/', views.placement_company_list, name='placement_company_list'),
    path('placement/companies/add/', views.placement_company_create, name='placement_company_create'),
    path('placement/companies/<int:company_id>/', views.placement_company_detail, name='placement_company_detail'),
    path('placement/companies/<int:company_id>/edit/', views.placement_company_edit, name='placement_company_edit'),
    path('placement/companies/<int:company_id>/delete/', views.placement_company_delete, name='placement_company_delete'),
    path('placement/companies/<int:company_id>/drives/add/', views.placement_drive_create, name='placement_company_drive_create'),
    path('placement/companies/<int:company_id>/students/add/', views.placement_assignment_create, name='placement_company_assignment_create'),
    path('placement/drives/', views.placement_drive_list, name='placement_drive_list'),
    path('placement/drives/add/', views.placement_drive_create, name='placement_drive_create'),
    path('placement/drives/<int:drive_id>/', views.placement_drive_detail, name='placement_drive_detail'),
    path('placement/drives/<int:drive_id>/edit/', views.placement_drive_edit, name='placement_drive_edit'),
    path('placement/drives/<int:drive_id>/assign-students/', views.placement_assign_students, name='placement_assign_students'),
    path('placement/drives/<int:drive_id>/students/add/', views.placement_assignment_create, name='placement_drive_assignment_create'),
    path('placement/drives/<int:drive_id>/interviews/schedule/', views.placement_interview_create, name='placement_drive_interview_create'),
    path('placement/students/', views.placement_student_list, name='placement_student_list'),
    path('placement/students/add/', views.placement_assignment_create, name='placement_assignment_create'),
    path('placement/students/<int:assignment_id>/edit/', views.placement_assignment_edit, name='placement_assignment_edit'),
    path('placement/students/<int:assignment_id>/interviews/schedule/', views.placement_interview_create, name='placement_assignment_interview_create'),
    path('placement/students/<int:assignment_id>/offer/', views.placement_offer_create, name='placement_assignment_offer_create'),
    path('placement/interviews/', views.placement_interview_list, name='placement_interview_list'),
    path('placement/interviews/schedule/', views.placement_interview_create, name='placement_interview_create'),
    path('placement/interviews/<int:interview_id>/edit/', views.placement_interview_edit, name='placement_interview_edit'),
    path('placement/offers/', views.placement_offer_list, name='placement_offer_list'),
    path('placement/offers/add/', views.placement_offer_create, name='placement_offer_create'),
    path('placement/offers/<int:offer_id>/edit/', views.placement_offer_edit, name='placement_offer_edit'),
    path('placement/reports/', views.placement_reports, name='placement_reports'),
    path('placement/export/', views.export_placement_report, name='export_placement_report'),
    path('<slug:section>/', views.simple_section, name='section'),
]
